In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier,plot_tree
from sklearn.metrics import accuracy_score,classification_report

In [3]:
Customer_details = pd.read_csv(r'C:\Users\User\Desktop\P\ECommerceSales\customer_details.csv')

In [4]:
Customer_details.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [5]:
Customer_details.shape

(3900, 18)

In [6]:
Customer_details.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [7]:
Customer_details.columns = (Customer_details.columns.str.strip().str.lower().str.replace(" ","_"))

In [8]:
Customer_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             3900 non-null   int64
 1   age                     3900 non-null   int64
 2   gender                  3900 non-null   object
 3   item_purchased          3900 non-null   object
 4   category                3900 non-null   object
 5   purchase_amount_(usd)   3900 non-null   int64
 6   location                3900 non-null   object
 7   size                    3900 non-null   object
 8   color                   3900 non-null   object
 9   season                  3900 non-null   object
 10  review_rating           3900 non-null   float64
 11  subscription_status     3900 non-null   object
 12  shipping_type           3900 non-null   object
 13  discount_applied        3900 non-null   object
 14  promo_code_used         3900 non-null   object
 15  previous_purchases      3900 non-null   int64
 16  payment_method          3900 non-null   object
 17  frequency_of_purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [9]:
Customer_details.duplicated().sum()

0

In [10]:
Customer_details.head()

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [11]:
Customer_details.to_csv(r'C:\Users\User\Desktop\P\ECommerceSales\cleaned_customer_details.csv',index=False)

In [12]:
product_details = pd.read_csv(r'C:\Users\User\Desktop\P\ECommerceSales\product_details.csv')

In [13]:
product_details.head()

,Uniqe Id,Product Name,Brand Name,Asin,Category,Upc Ean Code,List Price,Selling Price,Quantity,Model Number,...,Product Url,Stock,Product Details,Dimensions,Color,Ingredients,Direction To Use,Is Amazon Seller,Size Quantity Variant,Product Description
0,4c69b61db1fc16e7013b43fc926e502d,"DB Longboards CoreFlex Crossbow 41"" Bamboo Fib...",NaN,NaN,Sports & Outdoors | Outdoor Recreation | Skate...,NaN,NaN,$237.68,NaN,NaN,...,https://www.amazon.com/DB-Longboards-CoreFlex-...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN
1,66d49bbed043f5be260fa9f7fbff5957,"Electronic Snap Circuits Mini Kits Classpack, ...",NaN,NaN,Toys & Games | Learning & Education | Science ...,NaN,NaN,$99.95,NaN,55324,...,https://www.amazon.com/Electronic-Circuits-Cla...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN
2,2c55cae269aebf53838484b0d7dd931a,3Doodler Create Flexy 3D Printing Filament Ref...,NaN,NaN,Toys & Games | Arts & Crafts | Craft Kits,NaN,NaN,$34.99,NaN,NaN,...,https://www.amazon.com/3Doodler-Plastic-Innova...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN
3,18018b6bc416dab347b1b7db79994afa,Guillow Airplane Design Studio with Travel Cas...,NaN,NaN,Toys & Games | Hobbies | Models & Model Kits |...,NaN,NaN,$28.91,NaN,142,...,https://www.amazon.com/Guillow-Airplane-Design...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN
4,e04b990e95bf73bbe6a3fa09785d7cd0,Woodstock- Collage 500 pc Puzzle,NaN,NaN,Toys & Games | Puzzles | Jigsaw Puzzles,NaN,NaN,$17.49,NaN,62151,...,https://www.amazon.com/Woodstock-Collage-500-p...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN

In [14]:
product_details.shape

(10002, 28)

In [15]:
product_details.isnull().sum()

Uniqe Id                     0
Product Name                 0
Brand Name               10002
Asin                     10002
Category                   830
Upc Ean Code              9968
List Price               10002
Selling Price              107
Quantity                 10002
Model Number              1770
About Product              273
Product Specification     1632
Technical Details          790
Shipping Weight           1138
Product Dimensions        9523
Image                        0
Variants                  7524
Sku                      10002
Product Url                  0
Stock                    10002
Product Details          10002
Dimensions               10002
Color                    10002
Ingredients              10002
Direction To Use         10002
Is Amazon Seller             0
Size Quantity Variant    10002
Product Description      10002
dtype: int64

In [16]:
product_details= product_details.dropna(axis=1,how='all')

In [17]:
product_details.isnull().sum()

Uniqe Id                    0
Product Name                0
Category                  830
Upc Ean Code             9968
Selling Price             107
Model Number             1770
About Product             273
Product Specification    1632
Technical Details         790
Shipping Weight          1138
Product Dimensions       9523
Image                       0
Variants                 7524
Product Url                 0
Is Amazon Seller            0
dtype: int64

In [18]:
product_details.columns = (product_details.columns.str.strip().str.lower().str.replace(" ","_"))

In [19]:
product_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10002 entries, 0 to 10001
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   uniqe_id               10002 non-null  object
 1   product_name           10002 non-null  object
 2   category               9172 non-null   object
 3   upc_ean_code           34 non-null     object
 4   selling_price          9895 non-null   object
 5   model_number           8232 non-null   object
 6   about_product          9729 non-null   object
 7   product_specification  8370 non-null   object
 8   technical_details      9212 non-null   object
 9   shipping_weight        8864 non-null   object
 10  product_dimensions     479 non-null    object
 11  image                  10002 non-null  object
 12  variants               2478 non-null   object
 13  product_url            10002 non-null  object
 14  is_amazon_seller       10002 non-null  object
dtypes: object(15)
memory usage: 1.1+ MB

In [20]:
product_details['weight_value'] = pd.to_numeric(product_details['shipping_weight'].str.extract(r"(\d+(?:\.\d+)?)")[0],errors='coerce')
product_details['weight_unit'] = (product_details['shipping_weight'].str.extract(r"([a-zA-Z]+)")[0].str.lower())

product_details.head()

,uniqe_id,product_name,category,upc_ean_code,selling_price,model_number,about_product,product_specification,technical_details,shipping_weight,product_dimensions,image,variants,product_url,is_amazon_seller,weight_value,weight_unit
0,4c69b61db1fc16e7013b43fc926e502d,"DB Longboards CoreFlex Crossbow 41"" Bamboo Fib...",Sports & Outdoors | Outdoor Recreation | Skate...,NaN,$237.68,NaN,Make sure this fits by entering your model num...,Shipping Weight: 10.7 pounds (View shipping ra...,NaN,10.7 pounds,NaN,https://images-na.ssl-images-amazon.com/images...,https://www.amazon.com/DB-Longboards-CoreFlex-...,https://www.amazon.com/DB-Longboards-CoreFlex-...,Y,10.7,pounds
1,66d49bbed043f5be260fa9f7fbff5957,"Electronic Snap Circuits Mini Kits Classpack, ...",Toys & Games | Learning & Education | Science ...,NaN,$99.95,55324,Make sure this fits by entering your model num...,Product Dimensions: 14.7 x 11.1 x 10.2...,The snap circuits mini kits classpack provides...,4 pounds,14.7 x 11.1 x 10.2 inches 4.06 pounds,https://images-na.ssl-images-amazon.com/images...,NaN,https://www.amazon.com/Electronic-Circuits-Cla...,Y,4.0,pounds
2,2c55cae269aebf53838484b0d7dd931a,3Doodler Create Flexy 3D Printing Filament Ref...,Toys & Games | Arts & Crafts | Craft Kits,NaN,$34.99,NaN,Make sure this fits by entering your model num...,ProductDimensions:10.3x3.4x0.8inches|ItemWeigh...,show up to 2 reviews by default No longer are ...,12.8 ounces,NaN,https://images-na.ssl-images-amazon.com/images...,NaN,https://www.amazon.com/3Doodler-Plastic-Innova...,Y,12.8,ounces
3,18018b6bc416dab347b1b7db79994afa,Guillow Airplane Design Studio with Travel Cas...,Toys & Games | Hobbies | Models & Model Kits |...,NaN,$28.91,142,Make 8 different Planes at one time. | Experim...,ProductDimensions:3.5x6.2x13inches|ItemWeight:...,Go to your orders and start the return Select ...,13.4 ounces,NaN,https://images-na.ssl-images-amazon.com/images...,NaN,https://www.amazon.com/Guillow-Airplane-Design...,Y,13.4,ounces
4,e04b990e95bf73bbe6a3fa09785d7cd0,Woodstock- Collage 500 pc Puzzle,Toys & Games | Puzzles | Jigsaw Puzzles,NaN,$17.49,62151,Make sure this fits by entering your model num...,ProductDimensions:1.9x8x10inches|ItemWeight:13...,show up to 2 reviews by default 100% Officiall...,13.4 ounces,NaN,https://images-na.ssl-images-amazon.com/images...,NaN,https://www.amazon.com/Woodstock-Collage-500-p...,Y,13.4,ounces

In [21]:
product_details['weight_lb'] = product_details['weight_value']
product_details.loc[product_details['weight_unit'].str.contains('ounce',na=False),'weight_lb'] = (
product_details.loc[product_details['weight_unit'].str.contains('ounce',na=False),'weight_value']/16)

In [22]:
product_details.head()

,uniqe_id,product_name,category,upc_ean_code,selling_price,model_number,about_product,product_specification,technical_details,shipping_weight,product_dimensions,image,variants,product_url,is_amazon_seller,weight_value,weight_unit,weight_lb
0,4c69b61db1fc16e7013b43fc926e502d,"DB Longboards CoreFlex Crossbow 41"" Bamboo Fib...",Sports & Outdoors | Outdoor Recreation | Skate...,NaN,$237.68,NaN,Make sure this fits by entering your model num...,Shipping Weight: 10.7 pounds (View shipping ra...,NaN,10.7 pounds,NaN,https://images-na.ssl-images-amazon.com/images...,https://www.amazon.com/DB-Longboards-CoreFlex-...,https://www.amazon.com/DB-Longboards-CoreFlex-...,Y,10.7,pounds,10.7000
1,66d49bbed043f5be260fa9f7fbff5957,"Electronic Snap Circuits Mini Kits Classpack, ...",Toys & Games | Learning & Education | Science ...,NaN,$99.95,55324,Make sure this fits by entering your model num...,Product Dimensions: 14.7 x 11.1 x 10.2...,The snap circuits mini kits classpack provides...,4 pounds,14.7 x 11.1 x 10.2 inches 4.06 pounds,https://images-na.ssl-images-amazon.com/images...,NaN,https://www.amazon.com/Electronic-Circuits-Cla...,Y,4.0,pounds,4.0000
2,2c55cae269aebf53838484b0d7dd931a,3Doodler Create Flexy 3D Printing Filament Ref...,Toys & Games | Arts & Crafts | Craft Kits,NaN,$34.99,NaN,Make sure this fits by entering your model num...,ProductDimensions:10.3x3.4x0.8inches|ItemWeigh...,show up to 2 reviews by default No longer are ...,12.8 ounces,NaN,https://images-na.ssl-images-amazon.com/images...,NaN,https://www.amazon.com/3Doodler-Plastic-Innova...,Y,12.8,ounces,0.8000
3,18018b6bc416dab347b1b7db79994afa,Guillow Airplane Design Studio with Travel Cas...,Toys & Games | Hobbies | Models & Model Kits |...,NaN,$28.91,142,Make 8 different Planes at one time. | Experim...,ProductDimensions:3.5x6.2x13inches|ItemWeight:...,Go to your orders and start the return Select ...,13.4 ounces,NaN,https://images-na.ssl-images-amazon.com/images...,NaN,https://www.amazon.com/Guillow-Airplane-Design...,Y,13.4,ounces,0.8375
4,e04b990e95bf73bbe6a3fa09785d7cd0,Woodstock- Collage 500 pc Puzzle,Toys & Games | Puzzles | Jigsaw Puzzles,NaN,$17.49,62151,Make sure this fits by entering your model num...,ProductDimensions:1.9x8x10inches|ItemWeight:13...,show up to 2 reviews by default 100% Officiall...,13.4 ounces,NaN,https://images-na.ssl-images-amazon.com/images...,NaN,https://www.amazon.com/Woodstock-Collage-500-p...,Y,13.4,ounces,0.8375

In [23]:
product_details = product_details.drop(columns=['shipping_weight','about_product','product_specification','technical_details','product_dimensions','image','variants','product_url'])

In [24]:
product_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10002 entries, 0 to 10001
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   uniqe_id          10002 non-null  object
 1   product_name      10002 non-null  object
 2   category          9172 non-null   object
 3   upc_ean_code      34 non-null     object
 4   selling_price     9895 non-null   object
 5   model_number      8232 non-null   object
 6   is_amazon_seller  10002 non-null  object
 7   weight_value      8863 non-null   float64
 8   weight_unit       8864 non-null   object
 9   weight_lb         8863 non-null   float64
dtypes: float64(2), object(8)
memory usage: 781.5+ KB

In [25]:

product_details['selling_price'] = (product_details['selling_price'].str.replace('$',"",regex=False)
                                  .str.replace(",","",regex=False))
product_details['selling_price'] = pd.to_numeric(product_details['selling_price'],errors='coerce')
product_details['selling_price'] = product_details['selling_price'].fillna(0)

In [26]:
product_details

,uniqe_id,product_name,category,upc_ean_code,selling_price,model_number,is_amazon_seller,weight_value,weight_unit,weight_lb
0,4c69b61db1fc16e7013b43fc926e502d,"DB Longboards CoreFlex Crossbow 41"" Bamboo Fib...",Sports & Outdoors | Outdoor Recreation | Skate...,NaN,237.68,NaN,Y,10.70,pounds,10.70000
1,66d49bbed043f5be260fa9f7fbff5957,"Electronic Snap Circuits Mini Kits Classpack, ...",Toys & Games | Learning & Education | Science ...,NaN,99.95,55324,Y,4.00,pounds,4.00000
2,2c55cae269aebf53838484b0d7dd931a,3Doodler Create Flexy 3D Printing Filament Ref...,Toys & Games | Arts & Crafts | Craft Kits,NaN,34.99,NaN,Y,12.80,ounces,0.80000
3,18018b6bc416dab347b1b7db79994afa,Guillow Airplane Design Studio with Travel Cas...,Toys & Games | Hobbies | Models & Model Kits |...,NaN,28.91,142,Y,13.40,ounces,0.83750
4,e04b990e95bf73bbe6a3fa09785d7cd0,Woodstock- Collage 500 pc Puzzle,Toys & Games | Puzzles | Jigsaw Puzzles,NaN,17.49,62151,Y,13.40,ounces,0.83750
...,...,...,...,...,...,...,...,...,...,...
9997,1a22f23576bfdfe5ed6c887dc117aab6,Remedia Publications REM536B Money Activity Bo...,Toys & Games | Learning & Education | Counting...,NaN,9.31,REM536B,Y,4.80,ounces,0.30000
9998,e11514dcf1f087887cd5ea0bd646d1fc,Trends International NFL La Chargers HG - Mobi...,Toys & Games | Arts & Crafts,NaN,6.99,NaN,Y,0.96,ounces,0.06000
9999,c00301a38560da2abc89c1f86ce4b267,NewPath Learning 10 Piece Science Owls and Owl...,Office Products | Office & School Supplies | E...,NaN,37.95,34-6015,Y,2.80,pounds,2.80000
10000,c2928dbf9796ceba44863a2736afb405,Disney Princess Do It Yourself Braid Set,Toys & Games | Arts & Crafts | Craft Kits,NaN,3.58,2888PRST,Y,6.10,ounces,0.38125
10001,2bb94aefc3467ed83860e0e2712d5f10,"Hasegawa Ladders Lucano Step Ladder, Orange",Home & Kitchen | Furniture | Kids' Furniture |...,NaN,152.27,ML2.0-4OR,Y,20.50,pounds,20.50000

In [27]:
product_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10002 entries, 0 to 10001
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   uniqe_id          10002 non-null  object
 1   product_name      10002 non-null  object
 2   category          9172 non-null   object
 3   upc_ean_code      34 non-null     object
 4   selling_price     10002 non-null  float64
 5   model_number      8232 non-null   object
 6   is_amazon_seller  10002 non-null  object
 7   weight_value      8863 non-null   float64
 8   weight_unit       8864 non-null   object
 9   weight_lb         8863 non-null   float64
dtypes: float64(3), object(7)
memory usage: 781.5+ KB

In [28]:
long_names = product_details[product_details['product_name'].astype(str).str.len() > 240]
print(len(long_names))

0

In [29]:
product_details[product_details.select_dtypes(include='object').columns] = product_details.select_dtypes(include='object').fillna("Unknown")

product_details[product_details.select_dtypes(exclude='object').columns] = product_details.select_dtypes(exclude='object').fillna(0)

product_details.head()

,uniqe_id,product_name,category,upc_ean_code,selling_price,model_number,is_amazon_seller,weight_value,weight_unit,weight_lb
0,4c69b61db1fc16e7013b43fc926e502d,"DB Longboards CoreFlex Crossbow 41"" Bamboo Fib...",Sports & Outdoors | Outdoor Recreation | Skate...,Unknown,237.68,Unknown,Y,10.7,pounds,10.7000
1,66d49bbed043f5be260fa9f7fbff5957,"Electronic Snap Circuits Mini Kits Classpack, ...",Toys & Games | Learning & Education | Science ...,Unknown,99.95,55324,Y,4.0,pounds,4.0000
2,2c55cae269aebf53838484b0d7dd931a,3Doodler Create Flexy 3D Printing Filament Ref...,Toys & Games | Arts & Crafts | Craft Kits,Unknown,34.99,Unknown,Y,12.8,ounces,0.8000
3,18018b6bc416dab347b1b7db79994afa,Guillow Airplane Design Studio with Travel Cas...,Toys & Games | Hobbies | Models & Model Kits |...,Unknown,28.91,142,Y,13.4,ounces,0.8375
4,e04b990e95bf73bbe6a3fa09785d7cd0,Woodstock- Collage 500 pc Puzzle,Toys & Games | Puzzles | Jigsaw Puzzles,Unknown,17.49,62151,Y,13.4,ounces,0.8375

In [30]:
product_details.head()

,uniqe_id,product_name,category,upc_ean_code,selling_price,model_number,is_amazon_seller,weight_value,weight_unit,weight_lb
0,4c69b61db1fc16e7013b43fc926e502d,"DB Longboards CoreFlex Crossbow 41"" Bamboo Fib...",Sports & Outdoors | Outdoor Recreation | Skate...,Unknown,237.68,Unknown,Y,10.7,pounds,10.7000
1,66d49bbed043f5be260fa9f7fbff5957,"Electronic Snap Circuits Mini Kits Classpack, ...",Toys & Games | Learning & Education | Science ...,Unknown,99.95,55324,Y,4.0,pounds,4.0000
2,2c55cae269aebf53838484b0d7dd931a,3Doodler Create Flexy 3D Printing Filament Ref...,Toys & Games | Arts & Crafts | Craft Kits,Unknown,34.99,Unknown,Y,12.8,ounces,0.8000
3,18018b6bc416dab347b1b7db79994afa,Guillow Airplane Design Studio with Travel Cas...,Toys & Games | Hobbies | Models & Model Kits |...,Unknown,28.91,142,Y,13.4,ounces,0.8375
4,e04b990e95bf73bbe6a3fa09785d7cd0,Woodstock- Collage 500 pc Puzzle,Toys & Games | Puzzles | Jigsaw Puzzles,Unknown,17.49,62151,Y,13.4,ounces,0.8375

In [31]:
import unicodedata
def clean_ascii(value):
    if pd.isna(value):
        return value
    
    value = str(value)
    #value = unicodedata.normalize("NFKC",value)
    value = value.encode("ascii",errors = "ignore").decode("ascii")
    
    return value.strip()

In [32]:
for column in product_details.columns:
    product_details[column] = product_details[column].apply(clean_ascii)
    
print("Total rows :", len(product_details))
print("Total columns :",len(product_details.columns))

Total rows : 10002
Total columns : 10

In [33]:
product_details.to_csv(r'C:\Users\User\Desktop\P\ECommerceSales\cleaned_product_details.csv',index=False,encoding='utf-8-sig')

In [34]:
ecommerce_details = pd.read_csv(r'C:\Users\User\Desktop\P\ECommerceSales\E-commerece_sales_data_2024.csv')

In [35]:
ecommerce_details.head()

,user id,product id,Interaction type,Time stamp
0,1,4c69b61db1fc16e7013b43fc926e502d,purchase,10-10-2023 08:00
1,2,66d49bbed043f5be260fa9f7fbff5957,view,11-10-2023 08:00
2,3,2c55cae269aebf53838484b0d7dd931a,like,12-10-2023 08:00
3,4,18018b6bc416dab347b1b7db79994afa,view,13-10-2023 08:00
4,5,e04b990e95bf73bbe6a3fa09785d7cd0,like,14-10-2023 08:00

In [36]:
ecommerce_details.shape

(2999, 4)

In [37]:
ecommerce_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2999 entries, 0 to 2998
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user id           2999 non-null   int64
 1   product id        2999 non-null   object
 2   Interaction type  2871 non-null   object
 3   Time stamp        2999 non-null   object
dtypes: int64(1), object(3)
memory usage: 93.8+ KB

In [38]:
ecommerce_details.isnull().sum()

user id               0
product id            0
Interaction type    128
Time stamp            0
dtype: int64

In [39]:
ecommerce_details.duplicated().sum()

0

In [40]:
ecommerce_details.columns = (ecommerce_details.columns.str.strip().str.lower().str.replace(" ","_"))

In [41]:
ecommerce_details

,user_id,product_id,interaction_type,time_stamp
0,1,4c69b61db1fc16e7013b43fc926e502d,purchase,10-10-2023 08:00
1,2,66d49bbed043f5be260fa9f7fbff5957,view,11-10-2023 08:00
2,3,2c55cae269aebf53838484b0d7dd931a,like,12-10-2023 08:00
3,4,18018b6bc416dab347b1b7db79994afa,view,13-10-2023 08:00
4,5,e04b990e95bf73bbe6a3fa09785d7cd0,like,14-10-2023 08:00
...,...,...,...,...
2994,2995,f5149cfb8e04d7b30bd7b4eaed6713b8,like,15-12-2023 08:00
2995,2996,82318e8acf79bbeb3cf685a2732fb630,view,16-12-2023 08:00
2996,2997,19d150365d798db47cccf1622b6ad754,purchase,17-12-2023 08:00
2997,2998,136c0aff3ab56bd3d138775fe90ef970,view,18-12-2023 08:00
2998,2999,a2c6dd69f022a658c5bcc2b3b52970f2,like,19-12-2023 08:00

In [42]:
ecommerce_details["time_stamp"] = pd.to_datetime(ecommerce_details["time_stamp"]).dt.strftime("%Y-%m-%d %H:%M:%S")

In [43]:
ecommerce_details

,user_id,product_id,interaction_type,time_stamp
0,1,4c69b61db1fc16e7013b43fc926e502d,purchase,2023-10-10 08:00:00
1,2,66d49bbed043f5be260fa9f7fbff5957,view,2023-11-10 08:00:00
2,3,2c55cae269aebf53838484b0d7dd931a,like,2023-12-10 08:00:00
3,4,18018b6bc416dab347b1b7db79994afa,view,2023-10-13 08:00:00
4,5,e04b990e95bf73bbe6a3fa09785d7cd0,like,2023-10-14 08:00:00
...,...,...,...,...
2994,2995,f5149cfb8e04d7b30bd7b4eaed6713b8,like,2023-12-15 08:00:00
2995,2996,82318e8acf79bbeb3cf685a2732fb630,view,2023-12-16 08:00:00
2996,2997,19d150365d798db47cccf1622b6ad754,purchase,2023-12-17 08:00:00
2997,2998,136c0aff3ab56bd3d138775fe90ef970,view,2023-12-18 08:00:00
2998,2999,a2c6dd69f022a658c5bcc2b3b52970f2,like,2023-12-19 08:00:00

In [44]:
ecommerce_details.to_csv(r'C:\Users\User\Desktop\P\ECommerceSales\cleaned_ecommerce_details.csv',index=False)

In [45]:
max_length = ecommerce_details.astype(str).apply(lambda x:x.str.len().max())
print(max_length)

user_id              4
product_id          32
interaction_type     8
time_stamp          19
dtype: int64